### ISSUE TITLE
Editor for "Rights around Data Sources"

### ISSUE THREAD

**Issue by gilesdring** [theodi/interactive-data-ethics-canvas#23]
https://www.sketch.com/s/1049cbd8-ab44-483f-8007-43f0d3a7347c/a/PGml7n8

**Comment by gilesdring** [comment]
@davetaz to update questions here

**Comment by davetaz** [comment]
1.  What basis or licence do you have for using this data? (Short text)
2.  Was the data collected for this project or another purpose? (Yes / No / Unset)
3.  Does the data contain any personal information?
4.  Does the data contain any commercially or otherwise sensitive information? (Yes / No / Unset)
5.  Additional notes related to this data source. (long text)
